# Starter pipeline: To deploy Azure K8s engine
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task:  AzureCLI@2
  inputs:
    azureSubscription: azure-sp-sa
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az group deployment create  --resource-group django-rg --template-file azuredeploy.json
    workingDirectory: 'aks-template-network'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

